# Generated by Django 2.1.1 on 2020-08-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='isPublished',
            new_name='is_published',
        ),
    ]
